# Generated by Django 5.0 on 2023-12-17 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EntityModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_name', models.CharField(max_length=200)),
                ('legal_code', models.CharField(max_length=8)),
                ('reg_date', models.DateField()),
                ('legal_agent', models.CharField(max_length=120)),
                ('legal_fund', models.FloatField()),
                ('legal_form', models.CharField(max_length=120)),
                ('legal_activity', models.CharField(blank=True, max_length=300, null=True)),
                ('legal_address', models.CharField(blank=True, max_length=300, null=True)),
                ('legal_phone', models.CharField(blank=True, max_length=24, null=True)),
                ('date_added', models.DateTimeField()),
            ],
        ),
    ]
