# Generated by Django 5.0 on 2023-12-17 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entitymodel',
            name='reg_date',
            field=models.CharField(max_length=12),
        ),
    ]
