# Generated by Django 5.0 on 2023-12-17 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_entitymodel_reg_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entitymodel',
            name='reg_date',
            field=models.DateField(),
        ),
    ]
